### ISSUE TITLE
Support for AF_UNIX sockets

### ISSUE THREAD

**Issue by yetamrra** [alexpevzner/sane-airscan-unstable#11]
Use case: On Chrome OS, we proxy IPP-over-USB through an AF_UNIX socket instead of a local TCP socket.  We do this to protect the tunnel endpoint: Because there's no access control on TCP, any local process can otherwise connect to and control the printer through the tunnel.  We'd like to be able to to do the same for eSCL-over-USB through the same tunnels.  Now that all of sane-airscan's socket creation and connection is handled in `http_query_connect()`, this looks like a pretty small change.

To connect through a local socket, you need the original URL and the local path to the socket.  The URL is still needed for the `/eSCL` part of the path and to indicate what should go into the Host: header.
  
I did a quick hack and confirmed that things seem to work if I just swap the TCP socket for a local socket, but this leaves the question of how to pass that path in from the frontend.

To summarize my understanding: Incoming eSCL device names either look like 

1.  `airscan:e0:Some name` where `Some name` is autodiscovered.  In this case it's a network device and there's no local socket.
1.  `airscan:e0:Some name` where `Some name` is in the config.  In this case, the config will have a line like `"Some name" = url, [optional protocol]`.
1.  `airscan:escl:Some name:url`, where `Some name` and `url` are supplied by the SANE frontend.

What do you think about allowing the URL for cases 2 and 3 to look something like `https://host:port/path@/socket/path`?  I'm pretty sure @ is technically a valid URL character, but I doubt any device is going to use a path that contains it.  If somebody does have such a device, they could encode it as %40 to eliminate the ambiguity.  Another possibility for getting a path into the URL field would be something like `unix:/socket/path:https://...`.  The advantage to this second option is that it matches what sane-escl uses.

**Comment by alexpevzner** [comment]
Is the UNIX socket path always the same?

**Comment by yetamrra** [comment]
No, they change for each USB device.

**Comment by alexpevzner** [comment]
Oops! Seems that I've already commented it but don't see my comment here...

I'd prefer to stay with URL syntax, as defined by RFC3986. In particular, because it will let to keep untouched the `http_uri_new_relative()` function, that computes relative URLs (required by eSCL and for handling HTTP redirection)

So I propose the following:
* `scheme` == "unix"
* AF_UNIX socket path encoded into `host`
* In this mode, `Http: localhost` header will be set automatically, which very well fits IPP-over-USB specification

The only problem, the `host` field of URL can't contain `/` character, while socket path will most likely contain them. I see two possible solutions:
1. Use standart `%`-escaping
2. Take socket name from `host` and directory from the configuration file

Personally I would prefer 2nd variant, it looks simple and adequate

**Comment by yetamrra** [comment]
To make sure I understand, your suggestion is that the device line would look something like `airscan:escl:Some name:unix://%2Frun%2Fippusb%2F04a9_1823.sock/eSCL`.  sane-airscan would then send the request to `/eSCL/...` through `/run/ippusb/04a9_1823.sock` and would use `Host: localhost` in the request.

If that sounds right, it sounds reasonable to me.  I can try prototyping it and report back in a couple of days.

**Comment by alexpevzner** [comment]
Yes. Or we can put `/run/ippusb` part into the configuration file, and device line will look as `airscan:escl:Some name:unix://04a9_1823.sock/eSCL`, which looks less ugly :-)

**Comment by yetamrra** [comment]
Implementing as a separate protocol turned out to be a bit more invasive than I had expected.  I have something mostly working.  I'll get it cleaned up and send for discussion next week.
